#version 450

layout (local_size_x=16, local_size_y=16) in;

layout (binding = 0) uniform sampler2D inputBlurred;
layout (binding = 1, r11f_g11f_b10f) readonly uniform image2D inputImage;
layout (binding = 2, r11f_g11f_b10f) writeonly uniform image2D outputImage;

void main()
{
	ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
	vec2 texCoord = coord/imageSize(outputImage);
	vec4 blur = texture(inputBlurred, texCoord);
	imageStore(outputImage, coord, imageLoad(inputImage, coord)+blur);
}