#version 450

layout (local_size_x=16, local_size_y=16) in;

layout (binding = 0, r11f_g11f_b10f) readonly uniform image2D inputImage;
layout (binding = 1, r11f_g11f_b10f) writeonly uniform image2D outputImage;

void main()
{
	ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
	vec3 color = vec3(0);
	for (int i=0;i<2;++i)
	{
		for (int j=0;j<2;++j)
		{
			vec3 c = imageLoad(inputImage, 2*coord+ivec2(i,j)).rgb;
			color = max(color,c);
		}
	}
	imageStore(outputImage, coord, vec4(color*0.1,1));
}